version: "3.9"
services:
    webserver-test1:
      build: .
      ports:
      - "8081:80"
      links:
      - mysql-web-container
    mysql-web-container:
      image: mysql
      ports:				
      - "3308:3306"
      environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
